apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: product
type: Opaque
data:
  DB_USER: cHJvZHVjdHVzZXI=         # productuser
  DB_PASSWORD: cHJvZHVjdHBhc3MxMjM=  # productpass123